"""add_airline_id_pk_to_airlines

Revision ID: 3826541a9cf4
Revises: ad2936c47475
Create Date: 2026-04-25 12:50:51.994641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3826541a9cf4'
down_revision: Union[str, Sequence[str], None] = 'ad2936c47475'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
