"""create flights and airports tables

Revision ID: 501b540c317c
Revises: 
Create Date: 2026-04-19 11:56:38.502201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '501b540c317c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airports',
    sa.Column('iata_code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('iata_code')
    )
    op.create_index(op.f('ix_airports_iata_code'), 'airports', ['iata_code'], unique=False)
    op.create_table('flights',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('flight_number', sa.String(length=10), nullable=True),
    sa.Column('airline', sa.String(length=100), nullable=False),
    sa.Column('origin_iata', sa.String(length=3), nullable=False),
    sa.Column('destination_iata', sa.String(length=3), nullable=False),
    sa.Column('departure_year', sa.Integer(), nullable=False),
    sa.Column('departure_month', sa.Integer(), nullable=True),
    sa.Column('departure_day', sa.Integer(), nullable=True),
    sa.Column('departure_time', sa.Time(), nullable=True),
    sa.Column('arrival_time', sa.Time(), nullable=True),
    sa.Column('aircraft_type', sa.String(length=50), nullable=True),
    sa.Column('cabin_class', sa.String(length=20), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_iata'], ['airports.iata_code'], ),
    sa.ForeignKeyConstraint(['origin_iata'], ['airports.iata_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flights')
    op.drop_index(op.f('ix_airports_iata_code'), table_name='airports')
    op.drop_table('airports')
    # ### end Alembic commands ###
