"""add user_id to flights

Revision ID: 544cef7fa217
Revises: 2015719156a5
Create Date: 2026-05-02 19:03:11.291586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '544cef7fa217'
down_revision: Union[str, Sequence[str], None] = '2015719156a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flights', sa.Column('user_id', sa.String(length=26), nullable=True))
    op.create_index(op.f('ix_flights_user_id'), 'flights', ['user_id'], unique=False)
    op.create_foreign_key(None, 'flights', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flights', type_='foreignkey')
    op.drop_index(op.f('ix_flights_user_id'), table_name='flights')
    op.drop_column('flights', 'user_id')
    # ### end Alembic commands ###
