"""add routes table

Revision ID: 83361d1f7794
Revises: 544cef7fa217
Create Date: 2026-08-03 20:18:36.139111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83361d1f7794'
down_revision: Union[str, Sequence[str], None] = '544cef7fa217'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('airline_iata', sa.String(length=2), nullable=False),
    sa.Column('origin_iata', sa.String(length=3), nullable=False),
    sa.Column('destination_iata', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['airline_iata'], ['airlines.iata_code'], ),
    sa.ForeignKeyConstraint(['destination_iata'], ['airports.iata_code'], ),
    sa.ForeignKeyConstraint(['origin_iata'], ['airports.iata_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('airline_iata', 'origin_iata', 'destination_iata', name='uq_route_airline_origin_destination')
    )
    op.create_index(op.f('ix_routes_airline_iata'), 'routes', ['airline_iata'], unique=False)
    op.create_index(op.f('ix_routes_destination_iata'), 'routes', ['destination_iata'], unique=False)
    op.create_index(op.f('ix_routes_origin_iata'), 'routes', ['origin_iata'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routes_origin_iata'), table_name='routes')
    op.drop_index(op.f('ix_routes_destination_iata'), table_name='routes')
    op.drop_index(op.f('ix_routes_airline_iata'), table_name='routes')
    op.drop_table('routes')
    # ### end Alembic commands ###
