"""add_airline_id_to_airlines

Revision ID: ad2936c47475
Revises: 501b540c317c
Create Date: 2026-04-25 12:49:30.877606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad2936c47475'
down_revision: Union[str, Sequence[str], None] = '501b540c317c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airlines',
    sa.Column('airline_id', sa.Integer(), nullable=False),
    sa.Column('iata_code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('airline_id'),
    sa.UniqueConstraint('iata_code')
    )
    op.create_index(op.f('ix_airlines_airline_id'), 'airlines', ['airline_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_airlines_airline_id'), table_name='airlines')
    op.drop_table('airlines')
    # ### end Alembic commands ###
